--------------------------------------------------------
--  File creato - domenica-ottobre-09-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CALENDARIO_LEZIONI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CALENDARIO_LEZIONI" 
   (	"NOME_DOCENTE" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"GIORNO" VARCHAR2(20 BYTE), 
	"GIORNO_S" VARCHAR2(20 BYTE), 
	"PRIMA" VARCHAR2(20 BYTE), 
	"SECONDA" VARCHAR2(20 BYTE), 
	"TERZA" VARCHAR2(20 BYTE), 
	"QUARTA" VARCHAR2(20 BYTE), 
	"QUINTA" VARCHAR2(20 BYTE), 
	"SESTA" VARCHAR2(20 BYTE), 
	"SETTIMA" VARCHAR2(20 BYTE), 
	"OTTAVA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INDEX_CL
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."INDEX_CL" ON "SYSTEM"."CALENDARIO_LEZIONI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALENDARIO_LEZIONI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CALENDARIO_LEZIONI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CALENDARIO_LEZIONI" MODIFY ("GIORNO" NOT NULL ENABLE);
